// clients/hops-vue/src/components/Hop.vue
<template>
    <div class="hop-item">
        <h2>{{hop.label}}</h2>
        <p>{{hop.description}}</p>
        <ul>
            <li>AKA: {{hop.aka}}</li>
            <li>Country: {{hop.countryOfOrigin.label}}</li>
        </ul>
    </div>
</template>

<style scoped>
</style>

<script>
import { mapState } from 'vuex';
import Vue from 'vue';

export default {
    name: 'Hop',
    props: {
        hop: {
            type: Object,
            default: null,
            required: true
        }
    },
    methods: {
    },
};
</script>

// clients/hops-react/src/hop.component.js
import React from 'react';

export default class Hop extends React.Component {
    render() {
        return (
            <div className="hop-item">
                <h2>{this.props.hop.label}</h2>
                <p>{this.props.hop.description}</p>
                <ul>
                    <li>AKA: {this.props.hop.aka}</li>
                    <li>Country: {this.props.hop.countryOfOrigin.label}</li>
                </ul>
            </div>
        );
    }
}
